<?xml version="1.0" encoding="UTF-8"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="materials.xacro" />
  <xacro:include filename="inertial_macros.xacro" />

  <xacro:include filename="mobile_base.xacro" />
  <xacro:include filename="arm.xacro" />

  <xacro:arg name="gazebo_sim" default="false" />
  <xacro:if value="$(arg gazebo_sim)">
    <xacro:include filename="my_robot.gazebo.xacro" />
    <!-- <xacro:include filename="camera.xacro" /> -->
  </xacro:if>
  <xacro:unless value="$(arg gazebo_sim)">
    <xacro:include filename="mobile_base.ros2_control.xacro" />
    <xacro:include filename="arm.ros2_control.xacro" />
  </xacro:unless>


  <joint name="mobile_base_arm_joint" type="fixed">
    <parent link="base_link" />
    <child link="arm_base_link" />
    <origin xyz="${base_length / 4} 0 ${base_height}" rpy="0 0 0" />
  </joint>
</robot>